### ISSUE TITLE
Click and Drag to move view

### ISSUE THREAD

**Issue by RPG-Alex** [RPG-Alex/project-julia#21]
Currently the click functionality clicks on a spot and jarringly moves that be the center. Maybe it would be better if it was a click and drag and the view would move accordingly, so clicking an dragging up brings the bottom view towards the middle etc.

**Comment by sparqxi** [comment]
yeah. absolutely , I wanted it

**Comment by RPG-Alex** [comment]
Implemented. Thanks!
